/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author MADEESHA
 */
public class CustomerView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerId = new javax.swing.JTextField();
        customerIdLable = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        customerNameLable = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        customerAddressLable = new javax.swing.JLabel();
        customerAdress = new javax.swing.JTextField();
        customerContactLable = new javax.swing.JLabel();
        customerContact = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        removeButoon = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        wrapper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerId.setBackground(new java.awt.Color(255, 255, 255));
        customerId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerId.setForeground(new java.awt.Color(0, 0, 51));
        customerId.setToolTipText("");
        customerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdActionPerformed(evt);
            }
        });
        jPanel1.add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 250, 40));

        customerIdLable.setBackground(new java.awt.Color(255, 255, 255));
        customerIdLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerIdLable.setForeground(new java.awt.Color(0, 0, 51));
        customerIdLable.setText("  Customer Id");
        customerIdLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        customerIdLable.setOpaque(true);
        jPanel1.add(customerIdLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 40));

        heading.setBackground(new java.awt.Color(51, 51, 255));
        heading.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(0, 0, 51));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Customers");
        heading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        heading.setOpaque(true);
        jPanel1.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 150, 50));

        customerNameLable.setBackground(new java.awt.Color(255, 255, 255));
        customerNameLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerNameLable.setForeground(new java.awt.Color(0, 0, 51));
        customerNameLable.setText("  Customer Name");
        customerNameLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        customerNameLable.setOpaque(true);
        jPanel1.add(customerNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 40));

        customerName.setBackground(new java.awt.Color(255, 255, 255));
        customerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerName.setForeground(new java.awt.Color(0, 0, 51));
        customerName.setToolTipText("");
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });
        jPanel1.add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 250, 40));

        customerAddressLable.setBackground(new java.awt.Color(255, 255, 255));
        customerAddressLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerAddressLable.setForeground(new java.awt.Color(0, 0, 51));
        customerAddressLable.setText("  Customer Adress");
        customerAddressLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        customerAddressLable.setOpaque(true);
        jPanel1.add(customerAddressLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 40));

        customerAdress.setBackground(new java.awt.Color(255, 255, 255));
        customerAdress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerAdress.setForeground(new java.awt.Color(0, 0, 51));
        customerAdress.setToolTipText("");
        customerAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAdressActionPerformed(evt);
            }
        });
        jPanel1.add(customerAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 250, 40));

        customerContactLable.setBackground(new java.awt.Color(255, 255, 255));
        customerContactLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerContactLable.setForeground(new java.awt.Color(0, 0, 51));
        customerContactLable.setText("  Customer Contact");
        customerContactLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        customerContactLable.setOpaque(true);
        jPanel1.add(customerContactLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, 40));

        customerContact.setBackground(new java.awt.Color(255, 255, 255));
        customerContact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerContact.setForeground(new java.awt.Color(0, 0, 51));
        customerContact.setToolTipText("");
        customerContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerContactActionPerformed(evt);
            }
        });
        jPanel1.add(customerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 250, 40));

        addButton.setText("Add");
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 40));

        updateButton.setText("Update");
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 40));

        removeButoon.setText("Remove");
        removeButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButoonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 110, 40));

        viewButton.setText("View");
        jPanel1.add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 110, 40));

        searchButton.setText("Search");
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 110, 40));

        wrapper.setIcon(new javax.swing.ImageIcon("D:\\Projects_Learn\\Fullstack\\Springboot Academy\\Java Desktop Application Development\\5 JDBC\\Codes\\1,2,3,4\\PoSApp\\src\\main\\java\\assets\\images\\background2.jpg")); // NOI18N
        jPanel1.add(wrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdActionPerformed

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void customerAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAdressActionPerformed

    private void customerContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerContactActionPerformed

    private void removeButoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButoonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButoonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel customerAddressLable;
    private javax.swing.JTextField customerAdress;
    private javax.swing.JTextField customerContact;
    private javax.swing.JLabel customerContactLable;
    private javax.swing.JTextField customerId;
    private javax.swing.JLabel customerIdLable;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel customerNameLable;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removeButoon;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewButton;
    private javax.swing.JLabel wrapper;
    // End of variables declaration//GEN-END:variables
}
